
package net.scilingo.tictactoe.service.contract;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ticTacToeService", targetNamespace = "http://tictactoe.scilingo.net/", wsdlLocation = "file:/Users/ajscilingo/IdeaProjects/TicTacToe-WebService/src/main/resources/Move.wsdl")
public class TicTacToeService
    extends Service
{

    private final static URL TICTACTOESERVICE_WSDL_LOCATION;
    private final static WebServiceException TICTACTOESERVICE_EXCEPTION;
    private final static QName TICTACTOESERVICE_QNAME = new QName("http://tictactoe.scilingo.net/", "ticTacToeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/ajscilingo/IdeaProjects/TicTacToe-WebService/src/main/resources/Move.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TICTACTOESERVICE_WSDL_LOCATION = url;
        TICTACTOESERVICE_EXCEPTION = e;
    }

    public TicTacToeService() {
        super(__getWsdlLocation(), TICTACTOESERVICE_QNAME);
    }

    public TicTacToeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TICTACTOESERVICE_QNAME, features);
    }

    public TicTacToeService(URL wsdlLocation) {
        super(wsdlLocation, TICTACTOESERVICE_QNAME);
    }

    public TicTacToeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TICTACTOESERVICE_QNAME, features);
    }

    public TicTacToeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicTacToeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MovePort
     */
    @WebEndpoint(name = "moveSoap11")
    public MovePort getMoveSoap11() {
        return super.getPort(new QName("http://tictactoe.scilingo.net/", "moveSoap11"), MovePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MovePort
     */
    @WebEndpoint(name = "moveSoap11")
    public MovePort getMoveSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://tictactoe.scilingo.net/", "moveSoap11"), MovePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TICTACTOESERVICE_EXCEPTION!= null) {
            throw TICTACTOESERVICE_EXCEPTION;
        }
        return TICTACTOESERVICE_WSDL_LOCATION;
    }

}
